# Generated by Django 4.2 on 2026-03-28 16:01

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("short_description", models.CharField(db_index=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Published", "Published"),
                            ("Deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=50,
                    ),
                ),
                ("description", froala_editor.fields.FroalaField()),
                ("tech_stack", models.CharField(db_index=True, max_length=200)),
                ("image", models.ImageField(upload_to="portfolio_images/")),
                ("github_link", models.URLField(blank=True, null=True)),
                ("live_link", models.URLField(blank=True, null=True)),
                (
                    "project_mode",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In Progress", "In Progress"),
                            ("Live", "Live"),
                            ("Testing", "Testing"),
                        ],
                        db_index=True,
                        default="In Progress",
                        max_length=50,
                    ),
                ),
                ("client_name", models.CharField(db_index=True, max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to="portolio.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["name", "slug"], name="portolio_ca_name_8d1137_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "slug")},
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["title", "slug"], name="portolio_po_title_5b6330_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together={("title", "slug")},
        ),
    ]
